config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resource :dashboard, only: :show do
      post :import_papers
    end
  end

  resources :users, only: [:index, :show]

  resources :papers, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
    member do
      post :add_author
    end

    resources :authors, only: [] do
      member do
        post :confirm_authorship
      end
    end
  end

  resource :profile, only: [:edit, :update]

  resources :labs, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      patch :archive
    end
    resources :memberships, only: [:new, :create]
    resources :posts, only: [:new, :create]
    resources :paper, only: [] do
      resources :posts, only: [:new, :create]
    end
  end

  resources :memberships, only: [] do
    member do
      patch :accept
      patch :deny
      patch :cancel
    end
  end


end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  has_many :created_labs, class_name: "Lab", foreign_key: :creator_id

  has_many :memberships, dependent: :destroy
  has_many :joined_labs, through: :memberships, source: :lab

  has_one :author, dependent: :destroy
  has_many :papers, through: :author

  has_many :posts, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :first_name, :last_name, presence: true
  validate :no_blank_search_keywords

  def no_blank_search_keywords
    if self.search_keywords.any?(&:blank?)
      errors.add(:search_keywords, "No search keywords field can remain blank.")
    end
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/views/users/index.html.erb
<div class="container">
  <div class="row">

    <div class="col-xs-12 col-sm-8 col-sm-offset-2 text-center">
      <h2>Users</h2>
    </div>

    <% @users.each do |user| %>
    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
      <div class="product product-small">
        <div class='product-body'>
          <% if user.avatar? %>
          <%= cl_image_tag user.avatar, width: 150, height: 150, crop: "fill", class: "product-image hidden-xs", alt: "No profile picture" %>
          <% else %>
          <%= cl_image_tag "http://lorempixel.com/300/300/abstract/2/", width: 150, height: 150, class: "product-image hidden-xs", alt: "No profile picture" %>
          <% end %>
          <h3><%= user.first_name.capitalize + " " + user.last_name.capitalize %></h3>
          <p><%= user.email %></p>
          <p><%#= user.job_description %></p>
          <p><%#= user.research_interests %></p>
          <%= link_to "", user_path(user.id), class: "product-link"%>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-lg-4">
      <div class="product-profile">
        <div id="profile-info">
          <% if @user.avatar? %>
          <%= cl_image_tag @user.avatar, width: 150, height: 150, crop: "fill", class: "product-image hidden-xs", alt: "No profile picture" %>
          <% else %>
          <%= cl_image_tag "http://lorempixel.com/300/300/abstract/2/", width: 150, height: 150, class: "product-image hidden-xs", alt: "No profile picture" %>
          <% end %>
          <h2><%= @user.first_name.capitalize %> <%= @user.last_name.capitalize %></h2>
          <p><%= @user.email %></p>
          <% if current_user == @user %>
          <%= link_to "Edit profile", edit_profile_path, class: "btn btn-yellow-inverted btn-long" %>
          <% end %>
        </div>
        <!-- Conditional for current user doesn't have labs -->
        <div id="lab-info">
          <h3>Lab Information</h3>
          <% if @user == current_user && !@user.joined_labs.first %>
          <p>Looks like you aren't in any labs.</p>
          <%= link_to "Create a Lab", new_lab_path %>
          <!-- Conditional for user doesn't have labs -->
          <% elsif !@user.joined_labs.first %>
          <p>Looks like <%= @user.first_name %> isn't in any labs.</p>
          <!-- Conditional for user has labs -->
          <% elsif @user.joined_labs.first %>
          <% @user.joined_labs.each do |lab| %>
          <% if !lab.archived? %>
          <div>
            <h5><%= lab.name.capitalize %></h5>
            <%= link_to "Go to lab", lab_path(lab) %>
          </div>
          <% end %>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-lg-8">
      <div id="career-info">
        <div class="padded">
          <h3>Job Description</h3>
          <p><%= @user.job_description %></p>
        </div>
        <div class="padded">
          <h3>Education</h3>
          <p><%= @user.education %></p>
        </div>
        <div class="padded">
          <h3>Research Interests</h3>
          <p><%= @user.research_interests %></p>
        </div>
        <div class="padded">
          <% if @user.author %>
          <h3>Papers</h3>
          <ul>
           <% @user.author.papers.each do |paper| %>
           <li>
             <%= link_to paper.title, paper_path(paper) %>
           </li>
           <% end %>
           <% end %>
         </ul>
       </div>
     </div>
   </div>
 </div>
</div>