config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resource :dashboard, only: :show do
      post :import_papers
    end
  end

  resources :users, only: [:index, :show]

  resources :papers, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
    member do
      post :add_author
    end

    resources :authors, only: [] do
      member do
        post :confirm_authorship
      end
    end
  end

  resource :profile, only: [:edit, :update]

  resources :labs, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      patch :archive
    end
    resources :memberships, only: [:new, :create]
    resources :posts, only: [:new, :create]
    resources :paper, only: [] do
      resources :posts, only: [:new, :create]
    end
  end

  resources :memberships, only: [] do
    member do
      patch :accept
      patch :deny
      patch :cancel
    end
  end


end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-4 text-center">
        <h2>Company</h2>
        <div class="footer-links"><a href="#">About</a></div>
        <div class="footer-links"><a href="#">Team</a></div>
      </div>
      <div class="col-xs-12 col-sm-4 text-center">
        <h2>Contact</h2>
        <div class="footer-links"><a href="mailto:admin@journal-link.com" target="_blank"><span class="fa fa-mail"></span>admin@journal-link.com</a></div>
      </div>
      <div class="col-xs-12 col-sm-4 text-center">
        <h2>Credit</h2>
        <div class="footer-links"><a href="https://www.ncbi.nlm.nih.gov/">NCBI Database PubMed</a></div>
      </div>
      <div class="col-xs-12 padded">
        <div class="text-center">Made with <i class="fa fa-heart"></i> in AMS</div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-journal">
  <!-- Logo -->
  <div>
    <%= link_to root_path, class: "navbar-journal-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>
  </div>
  <!-- Search bar -->
<!--   <form action="/papers" class="navbar-form navbar-right" id="navbar" role="search">
    <div class="input-group">
      <input type="text" class="form-control" placeholder="Search Papers" name="search">
    </div>
    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
  </form> -->
  <!-- Right Navigation -->
  <div class="navbar-journal-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
    <!-- Links (when logged in) -->
    <%= link_to "My feed", papers_path, class: "navbar-journal-item navbar-journal-link" %>
    <%= link_to "My labs", labs_path, class: "navbar-journal-item navbar-journal-link" %>
    <!-- Avatar with dropdown menu -->
    <div class="navbar-journal-item">
      <div class="dropdown">
        <!-- Cloudinary image tag -->
        <% if current_user.avatar? %>
        <%= cl_image_tag current_user.avatar, width: 50, height: 50, gravity: :face, crop: :thumb, class: "avatar-large dropdown-toggle", id: "navbar-journal-menu", "data-toggle" => "dropdown" %>
        <% else %>
        <%= cl_image_tag "http://lorempixel.com/300/300/abstract/2/", width: 50, height: 50, gravity: :face, crop: :thumb, class: "avatar-large dropdown-toggle", id: "navbar-journal-menu", "data-toggle" => "dropdown" %>
        <% end %>
        <!-- Dropdown -->
        <ul class="dropdown-menu dropdown-menu-right navbar-journal-dropdown-menu">
          <li>
            <%= link_to user_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to root_path do %>
            <i class="fa fa-home"></i> <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i> <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <% else %>
    <!-- Login (when logged out) -->
    <%= link_to t(".sign_in", default: "Log in"), new_user_session_path, class: "navbar-journal-item navbar-journal-link" %>
    <% end %>
  </div>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-journal-item hidden-md hidden-lg">
    <div class="dropdown">
      <i id="icon-dropdown" class="fa fa-bars dropdown-toggle fa-2x" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-journal-dropdown-menu">
        <% if user_signed_in? %>
        <li><%= link_to t(".profile", default: "Home"), root_path %></li>
        <li><%= link_to t(".profile", default: "Profile"), user_path(current_user) %></li>
        <li><%= link_to "My feed", papers_path, class: "navbar-journal-item navbar-journal-link" %></li>
        <li><%= link_to "My labs", labs_path, class: "navbar-journal-item navbar-journal-link" %></li>
        <li><%= link_to t(".sign_out", default: "Log out"), destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to t(".sign_in", default: "Log in"), new_user_session_path, class: "navbar-journal-item navbar-journal-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>