config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resource :dashboard, only: :show do
      post :import_papers
    end
  end

  resources :users, only: [:index, :show]

  resources :papers, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
    member do
      post :add_author
    end

    resources :authors, only: [] do
      member do
        post :confirm_authorship
      end
    end
  end

  resource :profile, only: [:edit, :update]

  resources :labs, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      patch :archive
    end
    resources :memberships, only: [:new, :create]
    resources :posts, only: [:new, :create]
    resources :paper, only: [] do
      resources :posts, only: [:new, :create]
    end
  end

  resources :memberships, only: [] do
    member do
      patch :accept
      patch :deny
      patch :cancel
    end
  end


end

app/models/paper.rb
class Paper < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :paper_authors, dependent: :destroy
  has_many :authors, through: :paper_authors
  has_many :posts, dependent: :destroy
  # validates :title, :source, :reference, presence: true

  def is_user_potential_author?(user, author)

    is_user_not_already_author = self.authors.all? { user.author != author }

    user_author_name = "#{user.last_name}"
    matching_names = author.name.include?(user_author_name)

    matching_names && is_user_not_already_author
  end
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  def index
    # keywords
    @keywords = params[:keywords].presence || current_user.search_keywords
    if @keywords.empty?
      @papers = []
    else
      conditions = []
      conditions_words = {}
      @keywords.each_with_index do |word, index|
        conditions << "title like :word_#{index} OR abstract like :word_#{index}"
        conditions_words["word_#{index}".to_sym] = "%#{word}%"
      end
      conditions = conditions.join(" OR ")
      @papers = Paper.where(conditions, conditions_words)
      if params[:date].present?
        @papers = @papers.where(date: params[:date])
      end
      @sources = @papers.distinct.pluck(:source)
      if params[:source].present?
        @papers = @papers.where(source: params[:source])
      end
      @papers = @papers.select { |paper| paper.date }.sort_by { |paper| paper.date}.reverse
    end
  end

  def show
    @paper = Paper.find(params[:id])
    @labs = current_user.joined_labs
    @review = Review.new
  end
end

app/views/papers/index.html.erb
<div class="container">
  <div class="row">
    <% if current_user.search_keywords.empty? %>
    <div class="col-xs-12">
      <h3 class="text-center">Set your search criteria in your profile</h3>
    </div>
    <% else %>
    <div class="col-xs-12 col-sm-4">
      <div class="card-search">
        <h3>Refine your search</h3>
        <%= form_tag papers_path, method: :get, class: "form-group" do%>
        <% current_user.search_keywords.each do |word| %>
        <label for="checkbox"><input class="form-controll" type="checkbox" id="checkbox" name="keywords[]" value="<%= word %>" <%='checked' if @keywords.include?(word) %>
          ><%= " " + word.capitalize %></label><br>
          <% end %>
          <div id="sandbox-container">
            <input type="text" class="form-control" name="date" value="<%= params[:date] %>">
          </div>
          <select name="source" id="">
            <option value="">All sources</option>
            <% @sources.each do |source| %>
            <option value="<%= source %>" <%= "selected" if params[:source] == source%>>
              <%= source %>
            </option>
            <% end %>
          </select>
          <input type="submit" value="Filter" class="btn btn-yellow-inverted btn-long button">
          <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-8">
        <% if @papers.empty? %>
        <h3 class="text-center">No results</h3>
        <% else %>
        <% @papers.each_with_index do |paper, index| %>
        <div class='paper'>
          <div class="paper-body">
          <%= link_to paper_path(paper), class: "paper-title" do %>
            <h3><%= paper.title %></h3>
            <% end %>
            <ul class="list-inline">
              <% paper.authors.each_with_index do |author, index| %>
              <% if index.even? %>
              <li><%= author.name %></li>
              <% else %>
              <li class="emphasis"><%= author.name %></li>
              <% end %>
              <% end %>
            </ul>
            <p class="date"><%= paper.date %> | <%= paper.source %> | doi: <%= paper.reference %></p>
            <%= link_to "Go to paper", paper_path(paper), class: "paper-link" %>
          </div>
        </div>
        <% end %>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
  <%= content_for(:after_js) do %>
  <script>
    $(document).ready(function(){
      $('#sandbox-container input').datepicker({
      });
    });
  </script>
  <% end %>

app/views/papers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <!-- Paper title -->
      <div>
        <h2 class="paper-title"><%= @paper.title %></h2>
      </div>
      <!-- Paper authors -->
      <div>
        <h3 class="paper-sub-heading">Authors</h3>
        <ul class="list-inline">
          <% @paper.authors.each do |author| %>
          <li>
            <%= author.name %>
            <% if @paper.is_user_potential_author?(current_user, author)  %>
            <%= link_to confirm_authorship_paper_author_path(@paper, author), method: :post do %>
            <i class="glyphicon glyphicon-education"></i>
            Claim authorship
            <% end %>
            <% end %>
          </li>
          <% end %>
        </ul>
      </div>
      <div>
        <h4><%= @paper.date %> | <%= @paper.source %> | <%= @paper.reference %></h4>
      </div>
      <!-- Paper abstract -->
      <div>
        <h3 class="paper-sub-heading">Abstract</h3>
        <p><%= @paper.abstract %></p>
      </div>
      <!-- Paper links -->
      <div>
        <%= link_to "Go to source", @paper.source_url, target: :_blank, class: "btn btn-yellow-inverted paper-btn-padding" %>
        <ul>
          <% @labs.each do |lab| %>
          <li>
            <%= link_to "Share with #{lab.name}", new_lab_paper_post_path(lab, @paper)%>
          </li>
          <% end %>
        </ul>
      </div>
      <!-- Create review -->
      <div>
        <h3>New review</h3>
        <div class="form-group" id="new-form">
          <%= simple_form_for([@paper, @review]) do |f|%>
          <%= f.input :content, class: "form-control" %>
          <%= f.button :submit, "Submit", class: "btn btn-yellow-inverted" %>
          <% end %>
        </div>
      </div>
      <!-- Index reviews -->
      <div>
        <h3>Reviews</h3>
        <!-- Conditional if no reviews -->
        <div>
          <% if @paper.reviews == [] %>
          <p> Currently no reviews.</p>
          <% end %>
        </div>
        <% @paper.reviews.sort_by { |review| review.created_at}.reverse.each do |review|%>
        <div class="message">
          <!-- Cloudinary image tag -->
          <% if review.user.avatar? %>
          <%= cl_image_tag review.user.avatar, width: 50, height: 50, gravity: :face, crop: :thumb, class: "avatar-large hidden-xs", alt: "No profile picture" %>
          <% else %>
          <%= cl_image_tag "http://lorempixel.com/300/300/abstract/2/", width: 50, height: 50, class: "avatar-large hidden-xs", alt: "No profile picture" %>
          <% end %>
          <div class="message-name">
            <div class="message-name">
              <h3><%= review.user.first_name %> <%= review.user.last_name %></h3>
              <p><%= review.created_at %></p>
            </div>
            <div class="message-body">
              <p><%= review.content %></p>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>