config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resource :dashboard, only: :show do
      post :import_papers
    end
  end

  resources :users, only: [:index, :show]

  resources :papers, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
    member do
      post :add_author
    end

    resources :authors, only: [] do
      member do
        post :confirm_authorship
      end
    end
  end

  resource :profile, only: [:edit, :update]

  resources :labs, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      patch :archive
    end
    resources :memberships, only: [:new, :create]
    resources :posts, only: [:new, :create]
    resources :paper, only: [] do
      resources :posts, only: [:new, :create]
    end
  end

  resources :memberships, only: [] do
    member do
      patch :accept
      patch :deny
      patch :cancel
    end
  end


end

app/models/lab.rb
class Lab < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  belongs_to :creator, class_name: "User"

  has_many :memberships, dependent: :destroy
  has_many :posts, dependent: :destroy
  validates :name, uniqueness: true
  validates :name, :description, presence: true

  def if_member?(user)
    self.memberships.not_cancelled.find_by_user_id(user.id)
  end
end

app/controllers/labs_controller.rb
class LabsController < ApplicationController
  before_action :set_lab, only: [:show, :edit, :update, :archive]

  def index
    if current_user
      @labs = current_user.joined_labs
    else
      redirect_to root_path
      flash[:alert] = "You must be logged in."
    end
  end

  def show
    if current_user
      @post = Post.new
      @available_members = @lab.memberships.accepted_members
    else
      redirect_to root_path
      flash[:alert] = "You must be logged in or be part of this lab."
    end
  end

  def new
    @lab = Lab.new
  end

  def create
    @lab = Lab.new(lab_params)
    @lab.creator = current_user
    if @lab.save
      @membership = Membership.new(status: "accepted")
      @membership.user = current_user
      @membership.lab = @lab
      @membership.save
      redirect_to lab_path(@lab)
      flash[:notice] = "Lab successfully created."
    else
      render 'new'
    end
  end

  def edit
    if @lab.archived?
      redirect_to root_path
      flash[:alert] = "Cannot edit an archived lab."
    elsif !current_user.joined_labs.include?(@lab) || !(current_user.memberships.find_by_lab_id(@lab).status == "accepted")
      redirect_to lab_path(@lab)
      flash[:alert] = "Only accepted members can edit."
    end
  end

  def update
    if @lab.update(lab_params)
      redirect_to lab_path(@lab)
      flash[:notice] = "Lab successfully updated."
    else
      render :edit
    end
  end

  def archive
    @lab.archived = true
    @lab.save
    redirect_to user_path(current_user)
    flash[:notice] = "Lab successfully archived."
  end

  private
  def lab_params
    params.require(:lab).permit(:name, :description, :photo, :photo_cache)
  end

  def set_lab
    @lab = Lab.find(params[:id])
  end
end

app/views/labs/_member_info.html.erb
<h3><%= membership.user.first_name.capitalize %> <%= membership.user.last_name.capitalize %></h3>
<p>Status: <strong><%= membership.status %></strong></p>

app/views/labs/_member_profile_picture.html.erb
<% if membership.user.avatar? %>
  <%= link_to user_path(membership.user.id) do %>
    <%= cl_image_tag membership.user.avatar, width: 150, height: 150, crop: "fill", class: "product-image hidden-xs", alt: "No profile picture" %>
  <% end %>
<% else %>
  <%= link_to user_path(membership.user.id) do %>
    <%= cl_image_tag "http://lorempixel.com/300/300/abstract/2/", width: 150, height: 150, class: "product-image hidden-xs", alt: "No profile picture" %>
  <% end %>
<% end %>

app/views/labs/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <div class="card-form">
        <h2>Edit Lab</h2>

        <div class="form-group">
          <%= simple_form_for(@lab, url: lab_path) do |f| %>
          <%= f.input :name, class: "form-control" %>
          <%= f.input :description, class: "form-control" %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.input :current_password, hint: "We need your current password to confirm your changes", required: true %>
          <%= f.button :submit, class: "btn btn-yellow-inverted button" %>
          <% end %>
        </div>

        <div>
          <ul class="list-unstyled list-inline">
            <li><%= link_to "Back to lab", lab_path(@lab) %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/labs/index.html.erb
<div class="container">
  <div class="row">

    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <h2><%= current_user.first_name.capitalize %>'s labs</h2>
    </div>

    <% @labs.each do |lab| %>
    <% if !lab.archived? %>
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <div class="product">
        <div class='product-body'>
          <h3><%= lab.name.capitalize %> <% if lab.creator == current_user %>(Creator)<% end %></h3>
          <p>Lab status: <strong><% if !lab.archived? %> active <% else %> archived <% end %></strong></p>
          <p>Membership status: <strong><%= current_user.memberships.find_by_lab_id(lab.id).status %></strong></p>
          <%= link_to "", lab_path(lab), class: "product-link" %>
        </div>
      </div>
    </div>
    <% end %>
    <% end %>

    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <% if !current_user.joined_labs.first || current_user.joined_labs.select { |lab| lab.archived? } == current_user.joined_labs %>
      <div class="no-lab-card">
        <div class="content">
          <div>
            <p>Looks like you aren't in any labs.</p>
            <p>Would you like to create one?</p>
            <%= link_to new_lab_path, class: "btn-yellow-inverted" do %>
            <i class="fa fa-check"></i>
            Create a Lab
            <% end %>
          </div>
          <div>
            <%= image_tag 'lab.svg' %>
          </div>
        </div>
      </div>
      <% end %>
    </div>

  </div>
</div>

app/views/labs/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
      <div class="card-form">
        <h2>New Lab</h2>

        <%= simple_form_for(@lab) do |f| %>
        <%= f.input :name, autofocus: true %>
        <%= f.input :description %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.button :submit, class: "btn btn-yellow-inverted button" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/labs/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 color-body">
      <h2><%= @lab.name %></h2>
    </div>
    <!-- Left -->
    <div class="col-xs-12 col-md-6 col-lg-4">

      <% @available_members.each do |membership| %>
      <!-- Membership user profile picture -->
      <% if membership.status == "accepted" %>
      <div class="product">
        <%= render "labs/member_profile_picture", membership: membership %>
        <div class='product-body red'>
          <%= render "labs/member_info", membership: membership %>
          <% if current_user == @lab.creator %>
          <% unless membership.user == current_user %>
          <%= link_to "Cancel", cancel_membership_path(membership), method: "patch" %>
          <% end %>
          <% end %>
        </div>
      </div>

      <% elsif current_user == membership.user %>
      <div class="product">
        <%= render "labs/member_profile_picture", membership: membership %>
        <div class='product-body'>
          <%= render "labs/member_info", membership: membership %>
          <%= link_to "Accept", accept_membership_path(membership), method: "patch" %>
          <div class='product-body red deny'>
            <%= link_to "Deny", deny_membership_path(membership), method: "patch" %>
          </div>
        </div>
      </div>

      <% elsif membership.status == "pending" %>
      <div class="product">
        <%= render "labs/member_profile_picture", membership: membership %>
        <div class='product-body red'>
          <%= render "labs/member_info", membership: membership %>
          <%#= link_to "Accept", accept_membership_path(membership), method: "patch" %>
          <% if current_user == @lab.creator %>
          <%= link_to "Cancel", cancel_membership_path(membership), method: "patch" %>
          <% end %>
        </div>
      </div>

      <% else %>
      <%# if current_user == @lab.creator || membership.user %>
      <div class="product">
        <%= render "labs/member_profile_picture", membership: membership %>
        <div class='product-body'>
          <%= render "labs/member_info", membership: membership %>
        </div>
      </div>
      <%# end %>
      <% end %>
      <% end %>
    </div>

    <!-- Right -->
    <div class="col-xs-12 col-md-6 col-lg-8 color-body">
      <!-- Lab banner -->
      <% if @lab.photo? %>

      <div class="banner banner-40vh" style="background-image: url(<%= cl_image_path @lab.photo, height: 300, width: 400, alt: "Lab photo" ; %>);">
        <!-- crop: :fill removed for demo -->

      </div>
      <% end %>
      <!-- Lab links -->
      <div class="product-body a">
        <ul class="list-inline padded">
          <!-- Invite a member -->
          <li>
            <%= link_to "Invite a member", new_lab_membership_path(@lab) %>
          </li>
          <!-- Conditional for "Archive lab" -->
          <% if current_user.created_labs.include?(@lab) %>
          <li><%= link_to "Archive lab", archive_lab_path(@lab), method: :patch, data: { confirm: "Are you sure?" } %></li>
          <% end %>
          <li><%= link_to "Edit lab", edit_lab_path(@lab) %></li>
          <%# if current_user == @only_accepted %>
          <li><%= link_to "Leave lab", cancel_membership_path(user_id: current_user.id), method: "patch", data: { confirm: "Are you sure?" } %></li>
          <%# end %>
        </ul>
      </div>
      <!-- Lab description -->
      <div class="padded color-body">
        <h3>Description</h3>
        <p><%= @lab.description %></p>
        <h5>
          Last updated: <%= @lab.updated_at.to_formatted_s(:short) %> | Created at: <%= @lab.created_at.to_formatted_s(:short) %>
        </h5>
      </div>
      <!-- Create post -->
      <div>
        <div class="form-group padded color-body" id="new-form">
          <h3>New Post</h3>
          <%= simple_form_for([@lab, @post]) do |f|%>
          <%= f.input :content, class: "form-control" %>
          <%= f.button :submit, class: "btn btn-yellow-inverted" %>
          <% end %>
        </div>
      </div>
      <!-- Index posts -->
      <div>
        <h3 class="padded color-body">Posts</h3>
        <!-- Conditional if no posts -->
        <div class="padded color-body">
          <% if @lab.posts == [] %>
          <p> Currently no posts, why not say hello to your lab?</p>
          <% end %>
        </div>
        <% @lab.posts.sort_by { |post| post.created_at}.reverse.each do |post|%>
        <div class="message">
          <!-- Cloudinary image tags -->
          <% if post.user.avatar? %>
          <%= cl_image_tag post.user.avatar, width: 50, height: 50, gravity: :face, crop: :thumb, class: "avatar-large hidden-xs avatar-padding", alt: "No profile picture" %>
          <% else %>
          <%= cl_image_tag "http://lorempixel.com/300/300/abstract/2/", width: 50, height: 50, gravity: :face, crop: :thumb, class: "avatar-large hidden-xs avatar-padding", alt: "No profile picture" %>
          <% end %>
          <div class="message-name">
            <h3><%= post.user.first_name %> <%= post.user.last_name %></h3>
            <p><%= post.created_at.strftime("%b %d, %H:%M") %></p>
          </div>
          <div class="message-body">
            <p><%= post.content %></p>
            <% if post.paper %>
            <!-- If post has paper_id linked -->
            <div class="product-body-paper-link">
              <%= link_to paper_path(post.paper) do %>
              <%= post.paper.title %>
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>